version: '3'
services:
#mssql docker
  hotelas-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - hotelasnet

  hotelas-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:HotelAS=Server=hotelas-sql,1433;Database=HotelAS;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5000:80
    networks:
      - hotelasnet      
    links:
      - hotelas-sql
    depends_on:
      - hotelas-sql
      
networks:
  hotelasnet:
    driver: bridge      