services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: 'rabbitmq_container'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks: 
      - hotelAS_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  hotelas_sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: ib210330_sqlserver
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrongPassword!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - hotelAS_network

  hotelas_webapi:
    restart: unless-stopped
    build:
      context: .
      dockerfile: SeminarskiRSII.WebApi/Dockerfile
    container_name: ib210330_api
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__HotelAS: "Server=hotelas_sqlserver;Database=IB210330;User Id=sa;Password=YourStrongPassword!;"
      RABBITMQ_HOST: rabbitMQ
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - hotelAS_network
    depends_on:
      - hotelas_sqlserver
      - rabbitMQ

  rabbitmq-consumer:
    restart: unless-stopped
    build:
      context: ./SeminarskiRSII.RabbitMQConsumer
    environment:
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USERNAME=adin.smajkic@gmail.com
      - SMTP_PASSWORD=ymec wxzp inqz vwzl
    depends_on:
      - hotelas_sqlserver
      - hotelas_webapi
      - rabbitMQ
    networks:
      - hotelAS_network

volumes:
  sqlserverdata:
  rabbitmq_data:

networks:
  hotelAS_network:
    driver: bridge